using System;
using System.IO;
using System.Linq;
using System.Text;

namespace Gytis0.SOManager.Editor.CodeGeneration
{
	public static class EnumGenerator
	{
		public static void Generate(Type type, string folder)
		{
			string enumName = type.Name.Replace("SO", "");

			var typeAssets = type.GetAssets(IncludeDeleted.NotDeleted);

			var sb = new StringBuilder();

			sb.AppendLine("// <auto-generated />");
			sb.AppendLine("// This file is generated by GameDataManager. Do not edit manually.");
			sb.AppendLine("using System;");
			sb.AppendLine();
			sb.AppendLine("namespace Gytis0.SOManager.Enums");
			sb.AppendLine("{");
			sb.AppendLine(string.Format("\tpublic enum {0}s", enumName));
			sb.AppendLine("\t{");

			int index = 0;

			foreach (var asset in typeAssets.OrderBy(a => a.EnumName))
			{
				if (string.IsNullOrWhiteSpace(asset.Name))
					throw new Exception(string.Format("Cannot generate enum, because '{0}' is invalid", asset.GetIdentifyingName()));
				sb.AppendLine(string.Format("\t\t{0} = {1},", asset.EnumName, index));
				asset.SetEnumId(index);
				index++;
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			if (!Directory.Exists(folder))
				Directory.CreateDirectory(folder);

			File.WriteAllText(string.Format("{0}/{1}s.cs", folder, enumName), sb.ToString());
		}
	}
}